services:
  studio:
    build:
      context: ../..
      dockerfile: ./apps/studio/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app_network

  api:
    depends_on:
      - database
    build:
      context: ../..
      dockerfile: ./apps/api/Dockerfile
    environment:
      - DATABASE_URI=mongodb://database:27017
      - NODE_ENV=development
    env_file:
      - ../../.env
    ports:
      - "9000:9000"
    networks:
      - app_network

  database:
    extends:
      file: docker-compose.db.yml
      service: database
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  database: