services:
  database:
    image: mongo:latest
    volumes:
      - database:/data/db
    ports:
      - "27017:27017"
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  database:
  redis:
    driver: local